build:
  version: "1.0"

loans:
  message: "Welcome to MyBank loans related prod APIs "
  contactDetails:
    name: "Sonali Babar - Product Owner"
    email: "sb@myybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956